#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: cbcat file1 [file2 ...]"
    exit 1
fi

for file in "$@"; do
    if [ -f "$file" ]; then
        extension="${file##*.}"
        
        if [[ "$file" != *.* ]]; then
            extension=""
        fi

        echo "$file"
        echo '```'"$extension"
        cat "$file"
        echo '```'
        echo ""
    else
        echo "Error: '$file' not found." >&2
    fi
done
